### ISSUE TITLE
Phantomjs exit error

### ISSUE THREAD

**Issue by amindunited** [parkji/grunt-jasmine-webpack#1]
Phantomjs hangs, causing errors if subsequent tests are run using phantom.
More details can be found at:
[Issue 78](https://github.com/gruntjs/grunt-lib-phantomjs/issues/78)
[Pull request 83](https://github.com/gruntjs/grunt-lib-phantomjs/pull/83)

This can be fixed by upgrading grunt-lib-phantomjs to v0.7.1

**Comment by parkji** [comment]
Fixed in #2. Thanks!
