### ISSUE TITLE
Add support for options.summary

### ISSUE THREAD

**Issue by mtoso** [parkji/grunt-jasmine-webpack#16]
Looking at [grunt-contrib-jasmine](https://github.com/gruntjs/grunt-contrib-jasmine) is possible to have a shorter report setting the [summary option](https://github.com/gruntjs/grunt-contrib-jasmine#optionssummary) at true.

I can try to make a PR to add this functionality if it is welcome.

**Comment by parkji** [comment]
Hey @mtoso sorry for my late reply to this. PRs are more than welcome so feel free to add this functionality :)

**Comment by eduran** [comment]
Hello. I'd also like to have this functionality, I'll create a PR to add this.

**Comment by parkji** [comment]
Fixed by @eduran in #17 . Thanks!
