### ISSUE TITLE
Warning: "Cannot read property '0' of null" when jasmine_webpack task is executed

### ISSUE THREAD

**Issue by cluick** [parkji/grunt-jasmine-webpack#24]
Hi folks,
I´m using grunt-jasmine-webpack version 1.0.1 on Windows and it always fails with the following warning:
```
Running "jasmine_webpack:test" (jasmine_webpack) task
Warning: Cannot read property '0' of null Use --force to continue.
```
I found out that the problem is on line 27 in jasmine_webpack.js, where the following statement is executed:
``var promisePolyfillPath = require.resolve('es6-promise-polyfill').match(/.*\/node_modules\/[^/]+\//)[0] + "promise.min.js"``
This fails on my system since the path contains backslashes instead of forward slashes (due to windows?).

I´m using the following node and grunt versions:
grunt-cli v1.2.0
grunt v0.4.5
node v6.10.2

Can you please have a look at this issue?

Thank you & best regards,
Christof.

**Comment by alexpelan** [comment]
@cluick Thanks for reporting - does that PR (#25) fix the issue for you? I don't have grunt setup on any of my Windows VMs at the moment.

**Comment by cluick** [comment]
The issue is resolved with your change. Thank you very much for fixing this immediately!

**Comment by alexpelan** [comment]
1.0.2 is now published with this fix
